### PR TITLE
polish up

### PR DESCRIPTION
**Pull request by 5c077yP**
Hey, I found your repo when looking for a hapi s3 proxy.

I'd like to use it in prod, but saw that some of your dependencies are out-dated and no tests are there. Also readme docu was kind of missing. So i polished up the code. I'm sorry that this is a rather big PR, but maybe if you have time you could check it. It contains a few changes that would require a major version upgrade.

changes
- **major** `key` and and `filename`functions should  return a **Promise**
- **minor** `bucket` can now also be a function (means it's not passed to constructor but to every `getObject` call)
- **minor** add `s3Params` to pass additional options to the s3 constructor
- **minor** if `filename` not given but `mode` !== `false` -> take the key's filename
- removed _Makefile_ and put commands to _package.json_
- update npm dependencies
- apply eslint rules from _airbnb/base_
- update readme
- added tests

### CODE REVIEW

**Comment by bjyoungblood** [comment]
This looks awesome! I keep meaning to come back and clean this module up and write some tests, but other stuff keeps coming up. I'll take a closer look at this over the weekend, but it looks great so far.

**Comment by 5c077yP** [comment]
Hey just a quick note. You might want to remove the `npm postinstall` script again. It's actually just necessary when working with github depenedencies, but since it will be build when publishing it, it's not needed to build it again after it was installed.

**Comment by 5c077yP** [comment]
btw. thanks for looking at it :+1:

**Comment by bjyoungblood** [comment]
Good catch. I'll update that and publish 1.0.1.

And no, thank you for contributing!

**Pull request closed without merging**
